/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package captchaproj;

import java.awt.image.BufferedImage;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;

/**
 *
 * @author lokesaheb
 */
public class TextPointsForm extends javax.swing.JFrame {
String pstr,tstr;
    /**
     * Creates new form TextPointsForm
     */
    public TextPointsForm() {
        pstr="";
        tstr="";
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtusrd = new javax.swing.JTextField();
        ccnv = new java.awt.Canvas();
        btnwidget = new javax.swing.JButton();
        btnregs = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtusrdi = new javax.swing.JTextField();
        btnwidgetx = new javax.swing.JButton();
        btnloginx = new javax.swing.JButton();
        tcnv = new java.awt.Canvas();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Text Points");

        jLabel1.setText("Username");

        ccnv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ccnvMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ccnvMouseClicked(evt);
            }
        });

        btnwidget.setText("Display Widget");
        btnwidget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnwidgetActionPerformed(evt);
            }
        });

        btnregs.setText("Register");
        btnregs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ccnv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtusrd, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(btnwidget)
                        .addGap(32, 32, 32)
                        .addComponent(btnregs)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtusrd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnwidget)
                    .addComponent(btnregs))
                .addGap(26, 26, 26)
                .addComponent(ccnv, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Register", jPanel1);

        jLabel2.setText("Username");

        btnwidgetx.setText("Display Widget");
        btnwidgetx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnwidgetxActionPerformed(evt);
            }
        });

        btnloginx.setText("Login");
        btnloginx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloginxActionPerformed(evt);
            }
        });

        tcnv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tcnvMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tcnv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtusrdi, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(btnwidgetx)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnloginx)))
                .addGap(35, 35, 35))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtusrdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnwidgetx)
                    .addComponent(btnloginx))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tcnv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Login", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnwidgetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnwidgetActionPerformed
        try {
            // TODO add your handling code here:
            BufferedImage imga = null;
            imga = ImageIO.read(getClass().getResource("/textcp/acrp.png"));
            ccnv.getGraphics().drawImage(imga, 0,0, null);
        } catch (IOException ex) {
            Logger.getLogger(TextPointsForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnwidgetActionPerformed

    private void ccnvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ccnvMouseClicked
        // TODO add your handling code here:
      
    }//GEN-LAST:event_ccnvMouseClicked

    private void ccnvMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ccnvMousePressed
        // TODO add your handling code here:
          int x=evt.getX();
        int y=evt.getY();
        pstr=pstr+x+"AND"+y+" ";
        System.out.println(pstr);
        
    }//GEN-LAST:event_ccnvMousePressed

    private void btnregsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregsActionPerformed
        // TODO add your handling code here:
       String usr=txtusrd.getText();
        try {
            // TODO add your handling code here:
            String JDBC_DRIVER = "com.mysql.jdbc.Driver";
            String DB_URL = "jdbc:mysql://localhost:3306/captchdb";
            
            //  Database credentials
            String USER = "root";
            String PASS = "";
            
            Connection conn = null;
            PreparedStatement stmt = null;
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection(DB_URL, USER, PASS);
            stmt = conn.prepareStatement("INSERT INTO texpointstbl(userid,passwd) VALUES(?,?)");
            stmt.setString(1,usr);
            stmt.setString(2,pstr);
            stmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "New User Added");
            txtusrd.setText("");
            pstr="";
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ClickTextOptionForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ClickTextOptionForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnregsActionPerformed

    private void btnwidgetxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnwidgetxActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            BufferedImage imga = null;
            imga = ImageIO.read(getClass().getResource("/textcp/acrp.png"));
            tcnv.getGraphics().drawImage(imga, 0,0, null);
        } catch (IOException ex) {
            Logger.getLogger(TextPointsForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnwidgetxActionPerformed

    private void btnloginxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginxActionPerformed
        // TODO add your handling code here:
        String usr=txtusrdi.getText();
     
        try {
            // TODO add your handling code here:
            String JDBC_DRIVER = "com.mysql.jdbc.Driver";
            String DB_URL = "jdbc:mysql://localhost:3306/captchdb";
            
            //  Database credentials
            String USER = "root";
            String PASS = "";
            
            Connection conn = null;
            PreparedStatement stmt = null;
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection(DB_URL, USER, PASS);
            stmt = conn.prepareStatement("SELECT * FROM texpointstbl WHERE userid=?");
            stmt.setString(1,usr);
            String gstr="";
            ResultSet rs=stmt.executeQuery();
            int ix=0;
            while(rs.next()){
             gstr=rs.getString("passwd");
            }
            
            
            System.out.println("COMPUTED:"+gstr);
            System.out.println("TRAID:"+tstr);
            String medp[]=resuste(gstr.trim());
            String chep[]=resuste(tstr);
            
            System.out.println("chep="+chep.length);
            System.out.println("medp"+medp.length);
            
            if(chep.length!=medp.length){
            JOptionPane.showMessageDialog(null, "Login Failed");
            }
            else
            {
                int arx[]=new int[chep.length];
            for(int i=0;i<chep.length;i+=2) {
               int x1=Integer.parseInt(medp[i]);
               int x2=Integer.parseInt(chep[i]);
               int y1=Integer.parseInt(medp[i+1]);
               int y2=Integer.parseInt(chep[i+1]);
               
               int zdx=x1-x2;
               int zdy=y1-y2;
               
               if(zdx>=-5 && zdx<=5 && zdy>=-5 && zdx<=5) 
               {
                arx[i]=1;
               }
               else
               {
                arx[i]=0;
               }
              }
            
            
                boolean flag=true;
               for(int i=0;i<arx.length;i++) {
                  if(arx[i]==0) {
                      flag=false;
                  }
               }
               
               if(flag==true) {
                JOptionPane.showMessageDialog(null,"Login Successful");
               }
               else
               {
                   JOptionPane.showMessageDialog(null,"Login Failed");
               }
            
            }
            
            
          
            
            
            
           
           tstr="";
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ClickTextOptionForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ClickTextOptionForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnloginxActionPerformed

    private void tcnvMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tcnvMousePressed
        // TODO add your handling code here:
         int x=evt.getX();
        int y=evt.getY();
        tstr=tstr+x+"AND"+y+" ";
        System.out.println("TSTR"+tstr);
    }//GEN-LAST:event_tcnvMousePressed

   static String [] resuste(String pstre) {
     StringTokenizer stk=new StringTokenizer(pstre," ");
        String strep[]=new String[stk.countTokens()];
        String sprd[]=null;
        int i=0;
        while(stk.hasMoreElements()) {
        //System.out.println(stk.nextToken());
        strep[i]=stk.nextToken();
        i++;
        }
        
        for(int c=0;c<strep.length;c++)
        {
          StringTokenizer ster=new StringTokenizer(strep[c],"AND");
          sprd=new String[ster.countTokens()];
          int jx=0;
          while(ster.hasMoreElements()) {
              sprd[jx]=ster.nextToken();
              System.out.println(sprd[jx]);
              jx++;
          }
        }
        return sprd;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TextPointsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TextPointsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TextPointsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TextPointsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TextPointsForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnloginx;
    private javax.swing.JButton btnregs;
    private javax.swing.JButton btnwidget;
    private javax.swing.JButton btnwidgetx;
    private java.awt.Canvas ccnv;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private java.awt.Canvas tcnv;
    private javax.swing.JTextField txtusrd;
    private javax.swing.JTextField txtusrdi;
    // End of variables declaration//GEN-END:variables
}
